# Generated by Django 5.1.7 on 2025-03-11 09:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_transaction_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='inventory',
            name='acquired_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skin',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skins/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('user', 'skin')},
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
